package unidad1
import java.util.Scanner

public class Swich {

int numero 1 
int numero 2

public static void main (String[] args){


	Scanner teclado = new Scanner(System.in);
	System.out.println ("Ingrese numero 1" + numero 1);
	numero 1= teclado.nextInt();
        System.out.println ("Ingrese numero 2 "+ numero 2);
	numero 2 = teclado.nextInt();
	suma = numero 1 + numero 2;
	System.out.println ("La suma de los dos es " + suma );





}


}
